# Comentamos todas las importaciones para evitar problemas con las dependencias
# cuando ejecutamos tests individuales
# from .metodos_de_prueba import *
# from .test_alumno import *
# from .test_app import *
# from .test_autoridad import *
# from .test_cargo import *
# from .test_categoria_cargo import *
# from .test_db import *
# from .test_departamento import *
# from .test_especialidad import *
# from .test_facultad import *
# from .test_grado import *
# from .test_grupo import *
# from .test_orientacion import *
# from .test_plan import *
# from .test_tipo_dedicacion import *
# from .test_tipo_doc import *
# from .test_tipo_especialidad import *
# from .test_universidad import *
