from .alumno_mapping import AlumnoMapping
from .area_mapping import AreaMapping
from .autoridad_mapping import AutoridadMapping
from .cargo_mapping import CargoMapping
from .categoria_cargo_mapping import CategoriaCargoMapping
from .departamento_mapping import DepartamentoMapping
from .especialidad_mapping import EspecialidadMapping
from .facultad_mapping import FacultadMapping
from .grado_mapping import GradoMapping
from .grupo_mapping import GrupoMapping
from .inscripcion_mapping import InscripcionMapping
from .materia_mapping import MateriaMapping
from .nota_mapping import NotaMapping
from .orientacion_mapping import OrientacionMapping
from .plan_mapping import PlanMapping
from .tipo_dedicacion_mapping import TipoDedicacionMapping
from .tipo_documento_mapping import TipoDocumentoMapping
from .tipo_especialidad_mapping import TipoEspecialidadMapping
from .universidad_mapping import UniversidadMapping
