from .alumno import Alumno
from .alumno_grupo import alumno_grupo
from .area import Area
from .autoridad import Autoridad
from .cargo import Cargo
from .categoria_cargo import CategoriaCargo
from .departamento import Departamento
from .especialidad import Especialidad
from .facultad import Facultad
from .grado import Grado
from .grupo import Grupo
from .inscripcion import Inscripcion
from .materia import Materia
from .orientacion import Orientacion
from .plan import Plan
from .tipo_dedicacion import TipoDedicacion
from .tipo_documento import TipoDocumento
from .tipo_especialidad import TipoEspecialidad
from .universidad import Universidad
